In [30]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
plt.style.use('seaborn-notebook')
%matplotlib inline

In [2]:
df = pd.read_csv('data/ready4model_v1.csv')

In [8]:
# Using 9 months period as y label
df['y_label'] = (df['p1_3'] + df['p4_6'] + df['p7_9']) > 0

In [37]:
df.head(15)

Unnamed: 0  business_id  short_inspect_date  risk_category  \
0            0         1757            20170928  Moderate Risk   
1            1         4864            20161206       Low Risk   
2            2        79782            20160503  Moderate Risk   
3            3        73840            20171207      High Risk   
4            4        76437            20160329      High Risk   
5            5        82123            20171207  Moderate Risk   
6            6         1146            20180223      High Risk   
7            7         3838            20180222       Low Risk   
8            8        38929            20160114       Low Risk   
9            9        81161            20160325       Low Risk   
10          10        85781            20160311  Moderate Risk   
11          11        82880            20160309       Low Risk   
12          12        16441            20161206       Low Risk   
13          13         2716            20160323  Moderate Risk   
14          14         3165            20170323       Low Risk   

    short_violation_id  p1_3  p4_6  p7_9  p10_12  p13_18  p19_24  p25_36  \
0               103131     0     0     5       0       0       0       6   
1               103157     0     6     0       0       0       3       5   
2               103120     4     0     2       0       0       2       3   
3               103105     0     5     0       0       0       0       6   
4               103113     0    11     0       0       0       0       6   
5               103131     0     3     0       0       0       8       8   
6               103103     6     0     0       0       0       0       8   
7               103142     7     0     0       0       0       2       1   
8               103139     0     0     7       0       0       4       3   
9               103149     1     0     3       2       0       2       4   
10              103124     6     0     3       0       0       0       5   
11              103148     0     0     0       3       0       0       6   
12              103154     0     6     0       0       0       0       5   
13              103131     0     5     0       0       0       0       5   
14              103149     0     0     0       0       0       5       7   

    y_label  
0      True  
1      True  
2      True  
3      True  
4      True  
5      True  
6      True  
7      True  
8      True  
9      True  
10     True  
11    False  
12     True  
13     True  
14    False

In [19]:
y = df['y_label']
X = df[['p10_12', 'p13_18', 'p19_24', 'p25_36']]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=38)

In [33]:
log_model = LogisticRegression()
log_model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
log_model.coef_

array([[-0.34358492,  0.        ,  0.02145066,  0.03528642]])

In [26]:
log_model.intercept_

array([0.58761082])

In [34]:
log_model.predict(X_test)

array([ True,  True,  True, ...,  True,  True, False])

In [35]:
log_model.score(X_test, y_test)

0.6659021406727829