In [18]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
plt.style.use('seaborn-notebook')
%matplotlib inline
import csv
import src.scrubbing_develop as scrubbing
import src.utility 
from sklearn.model_selection import cross_val_score

In [19]:
feature_names = ['p7_9','p10_12', 'p13_18', 'p19_24', 'p25_36', '94013', '94014', '94080', '94101', '94102', '94103', '94104',
       '94105', '94107', '94108', '94109', '94110', '94111', '94112', '94114',
       '94115', '94116', '94117', '94118', '94120', '94121', '94122', '94123',
       '94124', '94127', '94129', '94130', '94131', '94132', '94133', '94134',
       '94143', '94158']

In [20]:
df2 = pd.read_pickle('data/sf_inspection_master.pkl')
df8 = scrubbing.remove_rows_zero_violation2(df2) 

In [21]:
y = df8['y_label']
X = df8[feature_names]

In [22]:
X_tr, X_test, y_tr, y_test = train_test_split(X, y, test_size=0.20, random_state=38)

In [23]:
X_train, X_validation, y_train, y_validation = train_test_split(X_tr, y_tr, test_size=0.25, random_state=28)

In [24]:
log_model = LogisticRegression()
log_model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
log_model.coef_

array([[-0.39537378, -0.24810847,  0.05936266,  0.17608496,  0.09377418,
         0.        ,  0.09457374,  0.        , -0.03105331, -0.26739064,
         0.3760721 ,  1.11390928, -0.15419409, -0.68824399, -0.02282375,
         1.27804426,  1.38275317, -0.38540261,  0.10557974,  0.64110243,
        -1.01998106,  0.35441938, -0.04074667, -0.22743686,  0.        ,
        -0.10563649,  0.45838487,  1.49008538, -0.42320245,  0.48955257,
         0.        , -0.31080494, -0.01058236,  0.58040068,  0.47383395,
         0.0684466 ,  0.17723918, -1.02159505]])

In [26]:
log_model.intercept_

array([-0.72561562])

In [27]:
log_model.score(X_validation, y_validation)

0.6928571428571428

In [28]:
scores = cross_val_score(log_model, X_tr, y_tr, cv=5)

In [29]:
scores

array([0.67515924, 0.68837803, 0.70242656, 0.66922095, 0.67305236])

In [30]:
sum(scores)/len(scores)

0.6816474282320977

In [31]:
log_model.score(X_test, y_test)

0.6887755102040817